//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankPassbook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class accountdetail
    {
        public int id { get; set; }
        public Nullable<long> accountNumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Name_Accountholder { get; set; }
        public Nullable<double> amt_credited { get; set; }
        public Nullable<double> amt_debited { get; set; }
        public Nullable<double> bal_amt { get; set; }
    
        public virtual accountSummary accountSummary { get; set; }
    }
}
