//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankPassbook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public int acc_id { get; set; }
        public System.DateTime Date { get; set; }
        public long Acc_No { get; set; }
        public string Name_AccountHolder { get; set; }
        public Nullable<double> amt_credited { get; set; }
        public Nullable<double> amt_debited { get; set; }
        public Nullable<double> Balance { get; set; }
    }
}
